# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c859a9c1405cb6f982c9bbd750711aa09b3c64c592a0fea24d829c1201f57f3ac9b5acfeafe11869b9e7a97742c2d2fc8a38fe13333ffbff63943d245f7bac7

test:
  secret_key_base: 846a5cb3b4cd5638c7325d042e3f9dabb32b07baa1454ac6fd315eba353d2159da57b05aac722d6bcb474bc1e380b30d8c759d65888fab7ec76dfa1d6eb1b97a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
